name: WorldGuard
main: WorldGuard\WorldGuard
version: 1.0.0
api: 1.6.0
author: Hmy2001
commands:
 /region:
  description: WorldGuard Command
  usage: "//region"
  permission: worldguard.command
permissions:
    worldguard:
        default: op
        description: "All the permissions to use the WorldGuard"
        children:
            worldguard.command:
                default: op
                description: "Allow the usage of the WorldGuard command"